name: "YtDlp"
version: "0.2"
slug: "ytdlp"
description: "A yt-dlp add on"
url: "https://github.com/clemens321/homeassistant-addons/tree/main/ytdlp"
arch:
  - amd64
map:
  - media:rw
image: "ghcr.io/clemens321/{arch}-addon-ytdlp"
